name: 'desafio_rmi_ds'
version: '1.0.0'
config-version: 2
profile: 'desafio_rmi_ds'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  desafio_rmi_ds:
    staging:
      materialized: view
    intermediate:
      materialized: view
    marts:
      materialized: table
