version: 2

models:
  - name: stg_educacao__aluno
    description: "Modelo de staging para a tabela aluno."
    columns:
      - name: id_aluno
        description: "ID único do aluno"
        tests:
          - unique
          - not_null
      - name: faixa_etaria
        description: "Faixa etária do aluno"
        tests:
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "^([0-9]+-[0-9]+|18\\+)$"
      - name: id_bairro
        description: "ID do bairro do aluno"

  - name: stg_educacao__escola
    description: "Modelo de staging para a tabela escola."
    columns:
      - name: id_escola
        description: "ID único da escola"
        tests:
          - unique
          - not_null
      - name: tipo
        description: "Tipo de escola (Fundamental, Médio)"
      - name: regiao
        description: "Região da escola"

  - name: stg_educacao__turma
    description: "Modelo de staging para a tabela turma."
    columns:
      - name: id_turma
        description: "ID único da turma"
        tests:
          - not_null
      - name: id_escola
        description: "ID da escola a qual a turma pertence"
      - name: serie
        description: "Série da turma"
      - name: turno
        description: "Turno da turma"
      - name: ano_letivo
        description: "Ano letivo da turma"
        tests:
          - not_null

  - name: stg_educacao__frequencia
    description: "Modelo de staging para a tabela frequencia."
    columns:
      - name: id_aluno
        description: "ID do aluno"
        tests:
          - not_null
          - relationships:
              to: ref('stg_educacao__aluno')
              field: id_aluno
      - name: id_turma
        description: "ID da turma"
        tests:
          - not_null
      - name: data_frequencia
        description: "Data do registro da frequência"
        tests:
          - not_null
      - name: status
        description: "Status da presença (Presente, Ausente)"

  - name: stg_educacao__avaliacao
    description: "Modelo de staging para a tabela avaliacao."
    columns:
      - name: id_aluno
        description: "ID do aluno"
        tests:
          - not_null
          - relationships:
              to: ref('stg_educacao__aluno')
              field: id_aluno
      - name: bimestre
        description: "Bimestre da avaliação"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 4
      - name: disciplina_1
        description: "Nota da disciplina 1"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.0
              max_value: 10.0
      - name: disciplina_2
        description: "Nota da disciplina 2"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.0
              max_value: 10.0
      - name: disciplina_3
        description: "Nota da disciplina 3"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.0
              max_value: 10.0
      - name: disciplina_4
        description: "Nota da disciplina 4"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.0
              max_value: 10.0
