name: dbt CD & Docs

on:
  push:
    branches:
      - main

jobs:
  deploy-and-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install dbt-duckdb

      - name: Run dbt deps
        run: dbt deps --profiles-dir .
        working-directory: ./

      - name: Run dbt run (production)
        run: dbt run --target prod --profiles-dir .
        working-directory: ./

      - name: Generate dbt docs
        run: dbt docs generate --target prod --profiles-dir .
        working-directory: ./

      - name: Deploy Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
